version: '3.1'

services:
  chainmgr:
    image: chainmgr
    build: .
    restart: always
    networks:
      - humun
    env_file: .env
    labels:
      traefik.enable: "false"
    volumes:
      - $PWD/config.json:/config.json

  chainmgrredis:
    image: redis
    restart: always
    networks:
      - humun
    labels:
      traefik.enable: "false"
    volumes:
      - redis:/data

networks:
  web:
    external: true
  humun:
    external: true

volumes:
  redis: