---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainmgr
  namespace: humun-core-crypto
  labels:
    app: chainmgr
spec:
  replicas: 10
  selector:
    matchLabels:
      app: chainmgr
  template:
    metadata:
      labels:
        app: chainmgr
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9090'
    spec:
      containers:
      - name: chainmgr
        image: registry.lestak.sh/humun-chainmgr:14
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 4000m
            memory: 4Gi
        envFrom:
          - secretRef:
              name: chainmgr
        ports:
          - containerPort: 9988
            name: http
            protocol: TCP
          - containerPort: 9090
            name: metrics
        volumeMounts:
        - name: config
          mountPath: "/config"
        livenessProbe:
          tcpSocket:
            port: 9988
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 9988
          initialDelaySeconds: 5
          periodSeconds: 3
      tolerations:
        - key: arch
          value: arm64
          operator: "Equal"
          effect: "PreferNoSchedule"
      volumes:
      - name: config
        configMap:
          name: chainmgr
          items:
          - key: "config.json"
            path: "config.json"
        
---
apiVersion: v1
kind: Service
metadata:
  name: chainmgr
  namespace: humun-core-crypto
  labels:
    app: chainmgr
spec:
  type: ClusterIP
  selector:
    app: chainmgr
  ports:
    - protocol: TCP
      port: 9988
      name: http
      targetPort: 9988
