---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chainmgr
  namespace: humun-core-crypto
data:
  config.json: |
    [
        {
            "name": "polygon-mumbai",
            "endpoints": [
                {
                    "endpoint": "http://54.218.81.122:8149",
                    "enabled": false
                }
            ]
        },
        {
            "name": "polygon",
            "endpoints": [
                {
                    "endpoint": "http://54.218.81.122:8145",
                    "enabled": true
                }
            ]
        },
        {
            "name": "ethereum",
            "endpoints": [
                {
                    "endpoint": "http://geth-mainnet.humun-core-nodes.svc.cluster.local.:8545",
                    "enabled": true
                }
            ]
        },
        {
            "name": "ethereum-ropsten",
            "endpoints": [
                {
                    "endpoint": "http://geth-ropsten.humun-core-nodes.svc.cluster.local.:8545",
                    "enabled": true
                }
            ]
        }
    ]